### Matrix and Vector Operations

#### Basics

In [1]:
import numpy as np


A = np.array([[2, 0, -1], [5, 7, 3], [-4, 1, 8], [9, 4, 6]])
B = np.array([[1, 1, 2], [2, -1, 6], [9, 5, 5]])
x = np.array([3, 0, -5, 2])


print("AB\n", A @ B, "\n")
print("A.Tx\n", A.T @ x, "\n")
print("BA.T\n", B @ A.T, "\n")
print("A.TA + B\n", A.T@A + B, "\n")
print("x.Tx - 3\n", x.T @ x - 3, "\n")

AB
 [[-7 -3 -1]
 [46 13 67]
 [70 35 38]
 [71 35 72]] 

A.Tx
 [ 44   3 -31] 

BA.T
 [[  0  18  13  25]
 [ -2  21  39  50]
 [ 13  95   9 131]] 

A.TA + B
 [[127  68  37]
 [ 69  65  59]
 [ 44  58 115]] 

x.Tx - 3
 35 



#### BLAS Routine

In [6]:
def gemm(alpha, A, B, beta, C):

    m, n = C.shape # A a m * p matrix, B a p * n matrix
    _, p = A.shape

    for i in range(m):
        for j in range(n):
            c = 0
            for k in range(p):
                c += A[i][k] * B[k][j]
            C[i][j] = alpha * c + beta * C[i][j]

    return C

n = 2^10
A = np.random.random((n, n))
B = np.random.random((n, n))
C = np.random.random((n, n))
alpha = 3
beta = -2


gemm(alpha, A, B, beta, C)


array([[364.63977937, 373.57548615, 373.38483763, ..., 380.53731713,
        375.55637614, 387.37631841],
       [354.06137055, 364.50110136, 375.96454727, ..., 376.82605882,
        360.146055  , 381.37008001],
       [352.81936138, 369.65401146, 359.87329586, ..., 362.05222558,
        360.80062633, 374.55147532],
       ...,
       [369.70361993, 383.02139544, 377.91598376, ..., 368.88385763,
        378.15552313, 400.04611617],
       [353.721704  , 352.03008977, 357.60473259, ..., 361.68867003,
        360.54238709, 375.22707194],
       [374.10899221, 378.95220059, 383.24242901, ..., 373.6537546 ,
        377.90054   , 399.07011735]])

In [ ]:
n = 2**15
A = np.random.random((n, n))
B = np.random.random((n, n))
C = np.random.random((n, n))
alpha = 3
beta = -2

alpha * A @ B + beta * C

numpy is considerably faster